#pragma once

#include "port_randomizer.h"

#include <cstddef>
#include <cstdint>
#include <vector>

// randomprime's skippable cutscenes (qol-cutscenes "skippable", MIT, see
// NOTICE): room script (SCLY) patches that let every cinematic be skipped,
// generated by tools/gen_skippable_cutscenes.py, plus a few engine tweaks at
// their call sites (grep PortSkipCutscenes::Active).
namespace PortSkipCutscenes {

// The setting, or forced on in randomizer and Archipelago games.
bool Active();
// True when a randomized game forces it on regardless of the setting.
bool Forced();

// Patches the SCLY section of area `mreaId` into `out`. Returns false (and
// leaves `out` empty) when not Active, when the room has no patch, or when
// the room's script doesn't match the disc (a mod replaced it).
// In Archipelago games it also applies randomprime's pickup patches
// (tools/gen_ap_pickup_patches.py), so pickups don't play their retail
// item's cutscene. In randomized games the Artifact Temple loses the central
// item's artifact theme and totem cinematic, and its totems give every hint.
bool PatchArea(uint32_t mreaId, const uint8_t* scly, size_t size, std::vector< uint8_t >& out);

// The disc's pickup model for a key from PortAp::MetroidPrime::PickupModelKey.
// False for keys without one (Power Beam, visors...).
bool PickupModel(int key, PortRandomizer::PickupModel& out);

// Whether a pickup model needs this resource (texture, skin, animation...).
// Such a resource may sit in another world's PAK, so CResLoader reads it from
// the disc when no loaded PAK has it.
bool IsPickupDependency(uint32_t id);

// Where randomprime puts a pickup showing `model`: the model's bounds (min xyz,
// max xyz) and the rotation (editor degrees) and scale such a pickup gets.
// False for models it has no bounds for.
struct PickupPlacement {
  float bounds[6];
  float rotation[3];
  float scale[3];
};
bool PickupPlacementFor(uint32_t model, PickupPlacement& out);

// Applies an op stream to a SCLY section (big-endian, as on the disc).
// Returns the number of ops whose target was missing; `out` holds the result
// either way. Exposed for tests.
int ApplyOps(const uint8_t* scly, size_t size, const uint8_t* ops, size_t opsSize,
             std::vector< uint8_t >& out);

// One script object of a SCLY section, for patches that depend on what the
// room holds. `props` is the property block as on the disc: the count, the
// NUL-terminated name, then the properties.
struct ScriptObject {
  int layer = 0;
  uint8_t type = 0;
  uint32_t id = 0;
  struct Connection {
    uint32_t state, message, target;
  };
  std::vector< Connection > connections;
  std::vector< uint8_t > props;
};
// Every object of a SCLY section, in order. False when it doesn't parse.
bool ScanObjects(const uint8_t* scly, size_t size, std::vector< ScriptObject >& out);

} // namespace PortSkipCutscenes
