#pragma once

#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

// Files built into the executable (MP_EMBED_RESOURCES, desktop builds): the
// controller-glyph textures under "textures/" and the pipeline cache seed
// "initial_pipeline_cache.db". Generated by tools/embed_resources.py. A build
// without them has an empty table, so every lookup misses.
namespace PortEmbedded {
struct Entry {
  const char* path; // relative, '/' separated, sorted
  const unsigned char* data;
  size_t size;
};

// Every entry, sorted by path.
std::span<const Entry> All();

// The bytes at `path`, or empty when there is no such entry.
std::span<const uint8_t> Find(std::string_view path);

// The entries whose path starts with `prefix` (give it a trailing '/' to select a folder).
std::span<const Entry> Under(std::string_view prefix);
} // namespace PortEmbedded
