#!/usr/bin/env python3
"""Writes a C++ source that embeds files as byte arrays plus a sorted lookup table.

usage: embed_resources.py OUT.cpp (--dir DIR PREFIX | --file FILE NAME)...

--dir adds every file under DIR as "PREFIX/<relative path>", --file adds one file as
NAME. The table (PortEmbedded::kTable / kCount, see platform/include/port_embedded.h)
is sorted by path so lookups can binary-search it. Bytes are written as hex literals,
which every compiler this port builds with (GCC, Clang, clang-cl) accepts.
"""
import os
import sys


def collect(args):
    entries = {}
    i = 0
    while i < len(args):
        if args[i] == "--dir":
            root, prefix = args[i + 1], args[i + 2].strip("/")
            for base, _, files in os.walk(root):
                for name in files:
                    full = os.path.join(base, name)
                    rel = os.path.relpath(full, root).replace(os.sep, "/")
                    entries[prefix + "/" + rel if prefix else rel] = full
            i += 3
        elif args[i] == "--file":
            entries[args[i + 2]] = args[i + 1]
            i += 3
        else:
            sys.exit("embed_resources.py: bad argument " + args[i])
    return sorted(entries.items())


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    out_path = sys.argv[1]
    entries = collect(sys.argv[2:])
    lines = [
        "// Generated by tools/embed_resources.py; do not edit.",
        '#include "port_embedded.h"',
        "namespace PortEmbedded {",
        "namespace {",
    ]
    for idx, (_, full) in enumerate(entries):
        with open(full, "rb") as f:
            data = f.read()
        # A zero-length array is not valid C++, so an empty file gets one pad byte
        # that the table's size does not count.
        body = data or b"\0"
        lines.append("const unsigned char d%d[] = {" % idx)
        for off in range(0, len(body), 32):
            lines.append(",".join("0x%02x" % b for b in body[off:off + 32]) + ",")
        lines.append("};")
    lines.append("} // namespace")
    lines.append("extern const Entry kTable[] = {")
    for idx, (path, full) in enumerate(entries):
        lines.append('{"%s", d%d, %d},' % (path, idx, os.path.getsize(full)))
    lines.append("};")
    lines.append("extern const unsigned long long kCount = %d;" % len(entries))
    lines.append("} // namespace PortEmbedded")
    tmp = out_path + ".tmp"
    with open(tmp, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.replace(tmp, out_path)


main()
