#!/usr/bin/env python3
"""Embed randomprime's custom pickup assets (extra_assets/, MIT, see NOTICE).

Usage: gen_custom_pickup_assets.py <randomprime>/extra_assets platform/port_custom_assets_data.inc

The port builds the Nothing, Zoomer, Cog, Phazon Suit and visor pickups from
these files plus disc models (platform/port_custom_res.cpp), as randomprime's
custom_assets.rs does, and the door shields of Archipelago's door types.
"""
import sys

FILES = [
    ('kNothingTxtrData', 'nothing_texture.txtr'),
    ('kPhazonSuitTxtr1Data', 'phazon_suit_texure_1.txtr'),
    ('kPhazonSuitTxtr2Data', 'phazon_suit_texure_2.txtr'),
    ('kZoomerCmdlData', 'zoomer.CMDL'),
    ('kCogCmdlData', 'cog.CMDL'),
    ('kDoorPowerHolorimData', 'power_beam_holorim.TXTR'),
    ('kDoorBombHolorimData', 'morph_ball_bombs_holorim.TXTR'),
    ('kDoorBombPatternData', 'orange.txtr'),
    ('kDoorBombColorData', 'testbnew.txtr'),
]


def main():
    src, out = sys.argv[1:3]
    with open(out, 'w') as f:
        f.write('// Generated by tools/gen_custom_pickup_assets.py from randomprime\'s\n'
                '// extra_assets (MIT, see NOTICE). Do not edit.\n')
        for name, path in FILES:
            data = open('%s/%s' % (src, path), 'rb').read()
            f.write('\n// %s\nstatic const unsigned char %s[%d] = {\n' % (path, name, len(data)))
            for i in range(0, len(data), 24):
                f.write('    ' + ','.join('0x%02X' % b for b in data[i:i + 24]) + ',\n')
            f.write('};\n')


if __name__ == '__main__':
    main()
